### ISSUE TITLE
Fix flaky tests/python/twitter/common/metrics/test_sampling.py

### ISSUE THREAD

**Issue by jsirois** [twitter/commons#221] opened 2014-02-24 21:02 UTC
See many times, one instance is here: https://travis-ci.org/twitter/commons/jobs/19526672
``` console
...
===================== 17 passed, 2 skipped in 0.56 seconds =====================
============================= test session starts ==============================
platform linux2 -- Python 2.7.3 -- py-1.4.20 -- pytest-2.5.2
collected 22 items / 1 skipped 
tests/python/twitter/common/metrics/test_rate.py ...
tests/python/twitter/common/metrics/test_metrics.py ..........
tests/python/twitter/common/metrics/test_sampling.py F..
tests/python/twitter/common/metrics/test_gauges.py ......
=================================== FAILURES ===================================
______________________________ test_sampler_base _______________________________
    def test_sampler_base():
      class TestSampler(SamplerBase):
        def __init__(self, period, clock):
          self.count = 0
          SamplerBase.__init__(self, period, clock)
    
        def iterate(self):
          self.count += 1
    
      test_clock = ThreadedClock()
      sampler = TestSampler(Amount(1, Time.SECONDS), clock=test_clock)
      sampler.start()
    
      test_clock.tick(0.5)
      assert sampler.count == 0
      test_clock.tick(0.5)
      assert sampler.count == 1
      test_clock.tick(5)
>     assert sampler.count == 6
E     assert 3 == 6
E      +  where 3 = <TestSampler(Thread-1 [TID=3394], started daemon 139778247915264)>.count
tests/python/twitter/common/metrics/test_sampling.py:50: AssertionError
------------------------------- Captured stdout --------------------------------
Time now: 0
Time now: 0.5
Time now: 1.0
Time now: 1.0
Time now: 2.0
Time now: 3.0
================ 1 failed, 21 passed, 1 skipped in 1.39 seconds ================
...
```

**Comment by Yasumoto** [comment] 2015-07-11 18:03
This is a dupe of #172

**Closed by Yasumoto** 2015-07-11 18:03 UTC
